---
title: "Hierarchical Clustering Complate Linkage"
output:
  html_document:
    df_print: paged
---


```{r}
USArrests
```

```{r}
summary(USArrests)
```

```{r}
df_complate <- data.frame(States=rownames(USArrests), USArrests)
par(las=2) # make label text perpendicular to axis
par(mar=c(5,8,4,2)) # increase y-axis margin.
barplot(df_complate$Murder, names.arg = df_complate$States, horiz = TRUE, cex.names = 0.5, xlab = "Murder Arrest per 100.000")
```

```{r}
barplot(df_complate$Assault, names.arg = df_complate$States, horiz = TRUE, cex.names = 0.5, xlab = "Assault Arrest per 100.000")
```

```{r}
barplot(df_complate$Rape, names.arg = df_complate$States, horiz = TRUE, cex.names = 0.5, xlab = "Rape Arrest per 100.000")
```

```{r}
barplot(df_complate$UrbanPop, names.arg = df_complate$States, horiz = TRUE, cex.names = 0.5, xlab = "Polulation in urban area")
```

```{r}
df_complate <- scale(df_complate[, 2:5])
d_complate <- dist(df_complate, method = "euclidean")
clusters_complate <- hclust(d_complate, method = "complete" )
plot(clusters_complate, cex = 0.6, hang = -1)
```

```{r}
plot(clusters_complate, cex = 0.6, hang = -1)
rect.hclust(clusters_complate, k = 4, border = 2:5)
```

